
// GenesysCloud version number: v1.8.0
#import <GenesysCloud/NRDefaultViewAdapter.h>
#import <GenesysCloud/NRContentTableViewCell.h>
#import <GenesysCloud/NRConversationalChannelCollectionViewCell.h>
#import <GenesysCloud/NRFeedbackTableViewCell.h>
#import <GenesysCloud/NRGroupTableViewCell.h>
#import <GenesysCloud/NRSuggestionTableViewCell.h>
#import <GenesysCloud/NRTableViewCell.h>
#import <GenesysCloud/NRTitleTableViewCell.h>
#import <GenesysCloud/ExtraData.h>
#import <GenesysCloud/NRChatFactory.h>
#import <GenesysCloud/InstantFeedbackHandler.h>
#import <GenesysCloud/NanorepPersonalInfoHandler.h>
#import <GenesysCloud/NRApplicationContentHandler.h>
#import <GenesysCloud/NRBotHandler.h>
#import <GenesysCloud/ChannelPickerDelegate.h>
#import <GenesysCloud/NRChanneCell.h>
#import <GenesysCloud/NRChannelingView.h>
#import <GenesysCloud/NRChannelingViewController.h>
#import <GenesysCloud/NRChannelPickerDelegate.h>
#import <GenesysCloud/NRChannelPresentor.h>
#import <GenesysCloud/NRChannelStrategy.h>
#import <GenesysCloud/NRPhoneChannelPresentor.h>
#import <GenesysCloud/NRCarouselQuickOption.h>
#import <GenesysCloud/NRQuickOption.h>
#import <GenesysCloud/NREntitiesProvider.h>
#import <GenesysCloud/BaseViewController.h>
#import <GenesysCloud/BrowserViewController.h>
#import <GenesysCloud/ChatComponentsViewController.h>
#import <GenesysCloud/InfoView.h>
#import <GenesysCloud/ViewConfiguration.h>
#import <GenesysCloud/NRAlertViewController.h>
#import <GenesysCloud/NRAlertviewTableViewCell.h>
#import <GenesysCloud/NRContextPickerViewController.h>
#import <GenesysCloud/NREmailChannelingPresentorViewController.h>
#import <GenesysCloud/NRLoadingViewController.h>
#import <GenesysCloud/NRNavigationViewController.h>
#import <GenesysCloud/NRNegativeFeedbackViewController.h>
#import <GenesysCloud/NRNoAnswerViewController.h>
#import <GenesysCloud/NRReadMoreViewController.h>
#import <GenesysCloud/NRWidgetViewController.h>
#import <GenesysCloud/LabelDelegate.h>
#import <GenesysCloud/SupportCenterDataSource.h>
#import <GenesysCloud/SupportCenterLabel.h>
#import <GenesysCloud/LabelTableViewCell.h>
#import <GenesysCloud/FAQViewController.h>
#import <GenesysCloud/SupportCenterBase.h>
#import <GenesysCloud/SupportCenterTableViewController.h>
#import <GenesysCloud/MultipleChoiceView.h>
#import <GenesysCloud/NoAnswersView.h>
#import <GenesysCloud/NRAbstractViews.h>
#import <GenesysCloud/NRAutoCompleteView.h>
#import <GenesysCloud/NRBaseNegativeFeedbckView.h>
#import <GenesysCloud/ConversationStateManager.h>
#import <GenesysCloud/NRConversationalLikeView.h>
#import <GenesysCloud/NRConversationlChannelView.h>
#import <GenesysCloud/NRCurrentContextView.h>
#import <GenesysCloud/NRCustomLabel.h>
#import <GenesysCloud/NRFeedbackViewFreeText.h>
#import <GenesysCloud/NRFeedbackViewMulti.h>
#import <GenesysCloud/NRFeedbackViewTextMulti.h>
#import <GenesysCloud/NRGroupsView.h>
#import <GenesysCloud/NRLikeView.h>
#import <GenesysCloud/NRNoAnswerView.h>
#import <GenesysCloud/NRNoConnectionView.h>
#import <GenesysCloud/NRResultPresntationDelegate.h>
#import <GenesysCloud/NRResultPresntationView.h>
#import <GenesysCloud/NRResult.h>
#import <GenesysCloud/NRResultsView.h>
#import <GenesysCloud/BLDCacheModel.h>
#import <GenesysCloud/BLDURLProtocol.h>
#import <GenesysCloud/BLDWKWebViewCache.h>
#import <GenesysCloud/FileUtil.h>
#import <GenesysCloud/NSString+BLDExtension.h>
#import <GenesysCloud/NSURLProtocol+WKWebView.h>
#import <GenesysCloud/NRChatView.h>
#import <GenesysCloud/NRURLProtocol.h>
#import <GenesysCloud/NRWebContentChannelPresentor.h>
#import <GenesysCloud/AccountProvider.h>
#import <GenesysCloud/AvailabilityResult.h>
#import <GenesysCloud/ChatAvailabilityChecker.h>
#import <GenesysCloud/BaseChatHandler.h>
#import <GenesysCloud/ChatHandler.h>
#import <GenesysCloud/ContentChatElement+Parser.h>
#import <GenesysCloud/ContentChatElement.h>
#import <GenesysCloud/PreChatInfo.h>
#import <GenesysCloud/ProactiveChatElement.h>
#import <GenesysCloud/ProactiveChatElementHandler.h>
#import <GenesysCloud/ProactiveChatElementHandlerDelegate.h>
#import <GenesysCloud/RemoteChatElement.h>
#import <GenesysCloud/StorableChatElement.h>
#import <GenesysCloud/ChatRecorder.h>
#import <GenesysCloud/AutoCompleteConfiguration.h>
#import <GenesysCloud/BoldFormConfiguration.h>
#import <GenesysCloud/IncomingBotTitleConfiguration.h>
#import <GenesysCloud/IncomingLiveConfiguration.h>
#import <GenesysCloud/InfoViewConfiguration.h>
#import <GenesysCloud/InstantFeedbackConfig.h>
#import <GenesysCloud/PersistentOptionConfiguration.h>
#import <GenesysCloud/ChatController.h>
#import <GenesysCloud/ChatControllerDelegate.h>
#import <GenesysCloud/ChatElement.h>
#import <GenesysCloud/LocalChatElement.h>
#import <GenesysCloud/ChatBarConfiguration.h>
#import <GenesysCloud/ChatConfiguration.h>
#import <GenesysCloud/ChatViewConfiguration.h>
#import <GenesysCloud/MessageConfiguration.h>
#import <GenesysCloud/IncomingBotConfiguration.h>
#import <GenesysCloud/MultipleSelectionConfiguration.h>
#import <GenesysCloud/QuickOptionConfiguration.h>
#import <GenesysCloud/ReadMoreViewConfiguration.h>
#import <GenesysCloud/SystemMessageConfiguration.h>
#import <GenesysCloud/TextConfiguration.h>
#import <GenesysCloud/ApplicationHandler.h>
#import <GenesysCloud/SpeechReconitionDelegate.h>
#import <GenesysCloud/StatementStatus.h>
#import <GenesysCloud/BLDError.h>
#import <GenesysCloud/BoldEvent.h>
#import <GenesysCloud/NSBundle+BLDUIBundle.h>
#import <GenesysCloud/UIColor+BLDUtility.h>
#import <GenesysCloud/UIColor+NanorepColors.h>
#import <GenesysCloud/UIImage+BLDBase64.h>
#import <GenesysCloud/UIView+BLDColorAnimation.h>
#import <GenesysCloud/ChatEventHandler.h>
#import <GenesysCloud/HandOver.h>
#import <GenesysCloud/ChatElementDelegate.h>
#import <GenesysCloud/HistoryItem.h>
#import <GenesysCloud/NSDictionary+BLDDefaultBranding.h>
#import <GenesysCloud/FileUploadInfo.h>
#import <GenesysCloud/ReadoutHandler.h>
#import <GenesysCloud/TextToSpeechParser.h>
#import <GenesysCloud/BoldFormSelection.h>
#import <GenesysCloud/BoldHandler.h>
#import <GenesysCloud/MessengerHandler.h>
#import <GenesysCloud/BrandedForm.h>
#import <GenesysCloud/BoldHandler+BCChatQueueDelegate.h>
#import <GenesysCloud/BoldHandler+BCChatRecaptureDelegate.h>
#import <GenesysCloud/BoldHandler+BCCreateChatSessionDelegate.h>
#import <GenesysCloud/BoldHandler+BCSubmitPreChatDelegate.h>
#import <GenesysCloud/BoldHandler+BCEmailChatHistoryDelegate.h>
#import <GenesysCloud/BoldHandler+BCSubmitUnavailableEmailCallDelegate.h>
#import <GenesysCloud/BoldHandler+ChatStateDelegate.h>
#import <GenesysCloud/BoldHandler+FileUpload.h>
#import <GenesysCloud/PreChatBrand.h>
#import <GenesysCloud/DefaultBoldFormSelection.h>
#import <GenesysCloud/LiveAccount.h>
#import <GenesysCloud/NSBundle+UIBoldBundle.h>
#import <GenesysCloud/NRNavigationBar.h>
#import <GenesysCloud/NRBasicSearchBar.h>
#import <GenesysCloud/NRSearchBar.h>
#import <GenesysCloud/NRSearchBarDelegate.h>
#import <GenesysCloud/NRDataSource.h>
#import <GenesysCloud/BoldForm.h>
#import <GenesysCloud/FormChatTableViewController.h>
#import <GenesysCloud/BoldCellInjector.h>
#import <GenesysCloud/CellInjectorFactory.h>
#import <GenesysCloud/RatingCellInjector.h>
#import <GenesysCloud/SelectCellInjector.h>
#import <GenesysCloud/EmailTextInjector.h>
#import <GenesysCloud/PhoneTextInjector.h>
#import <GenesysCloud/TextCellInjector.h>
#import <GenesysCloud/BoldCellData.h>
#import <GenesysCloud/BoldTableViewCell.h>
#import <GenesysCloud/RatingTableViewCell.h>
#import <GenesysCloud/SelectTableViewCell.h>
#import <GenesysCloud/TextTableViewCell.h>
#import <GenesysCloud/BoldHandler+BCSubmitPostChatDelegate.h>
#import <GenesysCloud/NRTextView.h>
#import <GenesysCloud/BoldHandler+BCChatMessageDelegate.h>
#import <GenesysCloud/BoldHandler+BCChatTyperDelegate.h>
#import <GenesysCloud/ChatTextView.h>
#import <GenesysCloud/FAQTableViewCell.h>
#import <GenesysCloud/MultilineTextTableViewCell.h>
#import <GenesysCloud/CustomFont.h>

// ===================================================================================================
// Copyright © 2021 GenesysCloud(Genesys).
// GenesysCloud SDK.
// All rights reserved.
// ===================================================================================================

#import <UIKit/UIKit.h>

//! Project version number for NanorepUI.
FOUNDATION_EXPORT double Bold360AIVersionNumber;

//! Project version string for NanorepUI.
FOUNDATION_EXPORT const unsigned char Bold360AIVersionString[];



